stages:
  clean_data:
    cmd: python src/scripts/run_cleaning.py
    deps:
      - data/raw/insurance_data.csv
      - src/scripts/run_cleaning.py
      - src/utils/cleaning_and_imputation_functions.py
    outs:
      - data/processed/insurance_data_cleaned.csv
    metrics:
      - metrics/summary.json